services:
  - type: web
    name: bank-recovery-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Bank Recovery Tracking"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: "base64:CZu67fKHGUj0V8VMAMEzpURulMj9I9KJ+8dDo4h33JM="
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: "Asia/Dhaka"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: "aws-0-ap-northeast-1.pooler.supabase.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: "postgres"
      - key: DB_USERNAME
        value: "postgres.wbgacppzdyqextjxlgwq"
      - key: DB_PASSWORD
        value: "5k44RWWPYqEZdu6H"
      - key: DB_SSLMODE
        value: "require"
      - key: DATABASE_URL
        value: "postgresql://postgres.wbgacppzdyqextjxlgwq:5k44RWWPYqEZdu6H@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local